name: Doe Soh Blog
baseurl: /blog
permalink: /:title.html
product: Doe Soh
gems: 
  - jekyll-assets
  - jekyll-last-modified-at
exclude: [vendor,Gemfile,Gemfile.lock,Rakefile,readme.md]
canonical_domain: https://www.doesoh.com
sugarcrm:
  extension_id: iccdnijlhdogaccaiafdpjmbakdcdakk
assets:
  js_compressor:  uglifier
  css_compressor: sass
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "page"
